/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.kroton;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class affiliation_updated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5245026499249765235L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"affiliation_updated\",\"namespace\":\"br.com.kroton\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"role\",\"type\":\"string\"},{\"name\":\"startDate\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"endDate\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\",\"logicalType\":\"timestamp-millis\"}],\"default\":null},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"primary\",\"type\":[\"null\",\"boolean\"],\"default\":null},{\"name\":\"updatedAt\",\"type\":[{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\",\"logicalType\":\"timestamp-millis\"}]},{\"name\":\"userUpdated\",\"type\":\"string\"}],\"connect.name\":\"affiliation_updated\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<affiliation_updated> ENCODER =
      new BinaryMessageEncoder<affiliation_updated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<affiliation_updated> DECODER =
      new BinaryMessageDecoder<affiliation_updated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<affiliation_updated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<affiliation_updated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<affiliation_updated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<affiliation_updated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this affiliation_updated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a affiliation_updated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a affiliation_updated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static affiliation_updated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence description;
   private java.lang.CharSequence role;
   private java.time.Instant startDate;
   private java.time.Instant endDate;
   private java.lang.CharSequence status;
   private java.lang.Boolean primary;
   private java.lang.Object updatedAt;
   private java.lang.CharSequence userUpdated;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public affiliation_updated() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param description The new value for description
   * @param role The new value for role
   * @param startDate The new value for startDate
   * @param endDate The new value for endDate
   * @param status The new value for status
   * @param primary The new value for primary
   * @param updatedAt The new value for updatedAt
   * @param userUpdated The new value for userUpdated
   */
  public affiliation_updated(java.lang.CharSequence id, java.lang.CharSequence description, java.lang.CharSequence role, java.time.Instant startDate, java.time.Instant endDate, java.lang.CharSequence status, java.lang.Boolean primary, java.lang.Object updatedAt, java.lang.CharSequence userUpdated) {
    this.id = id;
    this.description = description;
    this.role = role;
    this.startDate = startDate;
    this.endDate = endDate;
    this.status = status;
    this.primary = primary;
    this.updatedAt = updatedAt;
    this.userUpdated = userUpdated;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return description;
    case 2: return role;
    case 3: return startDate;
    case 4: return endDate;
    case 5: return status;
    case 6: return primary;
    case 7: return updatedAt;
    case 8: return userUpdated;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    case 2: role = (java.lang.CharSequence)value$; break;
    case 3: startDate = (java.time.Instant)value$; break;
    case 4: endDate = (java.time.Instant)value$; break;
    case 5: status = (java.lang.CharSequence)value$; break;
    case 6: primary = (java.lang.Boolean)value$; break;
    case 7: updatedAt = value$; break;
    case 8: userUpdated = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'role' field.
   * @return The value of the 'role' field.
   */
  public java.lang.CharSequence getRole() {
    return role;
  }


  /**
   * Sets the value of the 'role' field.
   * @param value the value to set.
   */
  public void setRole(java.lang.CharSequence value) {
    this.role = value;
  }

  /**
   * Gets the value of the 'startDate' field.
   * @return The value of the 'startDate' field.
   */
  public java.time.Instant getStartDate() {
    return startDate;
  }


  /**
   * Sets the value of the 'startDate' field.
   * @param value the value to set.
   */
  public void setStartDate(java.time.Instant value) {
    this.startDate = value;
  }

  /**
   * Gets the value of the 'endDate' field.
   * @return The value of the 'endDate' field.
   */
  public java.time.Instant getEndDate() {
    return endDate;
  }


  /**
   * Sets the value of the 'endDate' field.
   * @param value the value to set.
   */
  public void setEndDate(java.time.Instant value) {
    this.endDate = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'primary' field.
   * @return The value of the 'primary' field.
   */
  public java.lang.Boolean getPrimary() {
    return primary;
  }


  /**
   * Sets the value of the 'primary' field.
   * @param value the value to set.
   */
  public void setPrimary(java.lang.Boolean value) {
    this.primary = value;
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public java.lang.Object getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.Object value) {
    this.updatedAt = value;
  }

  /**
   * Gets the value of the 'userUpdated' field.
   * @return The value of the 'userUpdated' field.
   */
  public java.lang.CharSequence getUserUpdated() {
    return userUpdated;
  }


  /**
   * Sets the value of the 'userUpdated' field.
   * @param value the value to set.
   */
  public void setUserUpdated(java.lang.CharSequence value) {
    this.userUpdated = value;
  }

  /**
   * Creates a new affiliation_updated RecordBuilder.
   * @return A new affiliation_updated RecordBuilder
   */
  public static Builder newBuilder() {
    return new affiliation_updated.Builder();
  }

  /**
   * Creates a new affiliation_updated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new affiliation_updated RecordBuilder
   */
  public static Builder newBuilder(affiliation_updated.Builder other) {
    if (other == null) {
      return new affiliation_updated.Builder();
    } else {
      return new affiliation_updated.Builder(other);
    }
  }

  /**
   * Creates a new affiliation_updated RecordBuilder by copying an existing affiliation_updated instance.
   * @param other The existing instance to copy.
   * @return A new affiliation_updated RecordBuilder
   */
  public static Builder newBuilder(affiliation_updated other) {
    if (other == null) {
      return new affiliation_updated.Builder();
    } else {
      return new affiliation_updated.Builder(other);
    }
  }

  /**
   * RecordBuilder for affiliation_updated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<affiliation_updated>
    implements org.apache.avro.data.RecordBuilder<affiliation_updated> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence description;
    private java.lang.CharSequence role;
    private java.time.Instant startDate;
    private java.time.Instant endDate;
    private java.lang.CharSequence status;
    private java.lang.Boolean primary;
    private java.lang.Object updatedAt;
    private java.lang.CharSequence userUpdated;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(affiliation_updated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.role)) {
        this.role = data().deepCopy(fields()[2].schema(), other.role);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.startDate)) {
        this.startDate = data().deepCopy(fields()[3].schema(), other.startDate);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.endDate)) {
        this.endDate = data().deepCopy(fields()[4].schema(), other.endDate);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.primary)) {
        this.primary = data().deepCopy(fields()[6].schema(), other.primary);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[7].schema(), other.updatedAt);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.userUpdated)) {
        this.userUpdated = data().deepCopy(fields()[8].schema(), other.userUpdated);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing affiliation_updated instance
     * @param other The existing instance to copy.
     */
    private Builder(affiliation_updated other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.role)) {
        this.role = data().deepCopy(fields()[2].schema(), other.role);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.startDate)) {
        this.startDate = data().deepCopy(fields()[3].schema(), other.startDate);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.endDate)) {
        this.endDate = data().deepCopy(fields()[4].schema(), other.endDate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.primary)) {
        this.primary = data().deepCopy(fields()[6].schema(), other.primary);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[7].schema(), other.updatedAt);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.userUpdated)) {
        this.userUpdated = data().deepCopy(fields()[8].schema(), other.userUpdated);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'role' field.
      * @return The value.
      */
    public java.lang.CharSequence getRole() {
      return role;
    }


    /**
      * Sets the value of the 'role' field.
      * @param value The value of 'role'.
      * @return This builder.
      */
    public Builder setRole(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.role = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'role' field has been set.
      * @return True if the 'role' field has been set, false otherwise.
      */
    public boolean hasRole() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'role' field.
      * @return This builder.
      */
    public Builder clearRole() {
      role = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'startDate' field.
      * @return The value.
      */
    public java.time.Instant getStartDate() {
      return startDate;
    }


    /**
      * Sets the value of the 'startDate' field.
      * @param value The value of 'startDate'.
      * @return This builder.
      */
    public Builder setStartDate(java.time.Instant value) {
      validate(fields()[3], value);
      this.startDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'startDate' field has been set.
      * @return True if the 'startDate' field has been set, false otherwise.
      */
    public boolean hasStartDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'startDate' field.
      * @return This builder.
      */
    public Builder clearStartDate() {
      startDate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'endDate' field.
      * @return The value.
      */
    public java.time.Instant getEndDate() {
      return endDate;
    }


    /**
      * Sets the value of the 'endDate' field.
      * @param value The value of 'endDate'.
      * @return This builder.
      */
    public Builder setEndDate(java.time.Instant value) {
      validate(fields()[4], value);
      this.endDate = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'endDate' field has been set.
      * @return True if the 'endDate' field has been set, false otherwise.
      */
    public boolean hasEndDate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'endDate' field.
      * @return This builder.
      */
    public Builder clearEndDate() {
      endDate = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'primary' field.
      * @return The value.
      */
    public java.lang.Boolean getPrimary() {
      return primary;
    }


    /**
      * Sets the value of the 'primary' field.
      * @param value The value of 'primary'.
      * @return This builder.
      */
    public Builder setPrimary(java.lang.Boolean value) {
      validate(fields()[6], value);
      this.primary = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'primary' field has been set.
      * @return True if the 'primary' field has been set, false otherwise.
      */
    public boolean hasPrimary() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'primary' field.
      * @return This builder.
      */
    public Builder clearPrimary() {
      primary = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public java.lang.Object getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public Builder setUpdatedAt(java.lang.Object value) {
      validate(fields()[7], value);
      this.updatedAt = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public Builder clearUpdatedAt() {
      updatedAt = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'userUpdated' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserUpdated() {
      return userUpdated;
    }


    /**
      * Sets the value of the 'userUpdated' field.
      * @param value The value of 'userUpdated'.
      * @return This builder.
      */
    public Builder setUserUpdated(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.userUpdated = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'userUpdated' field has been set.
      * @return True if the 'userUpdated' field has been set, false otherwise.
      */
    public boolean hasUserUpdated() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'userUpdated' field.
      * @return This builder.
      */
    public Builder clearUserUpdated() {
      userUpdated = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public affiliation_updated build() {
      try {
        affiliation_updated record = new affiliation_updated();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.role = fieldSetFlags()[2] ? this.role : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.startDate = fieldSetFlags()[3] ? this.startDate : (java.time.Instant) defaultValue(fields()[3]);
        record.endDate = fieldSetFlags()[4] ? this.endDate : (java.time.Instant) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.primary = fieldSetFlags()[6] ? this.primary : (java.lang.Boolean) defaultValue(fields()[6]);
        record.updatedAt = fieldSetFlags()[7] ? this.updatedAt :  defaultValue(fields()[7]);
        record.userUpdated = fieldSetFlags()[8] ? this.userUpdated : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<affiliation_updated>
    WRITER$ = (org.apache.avro.io.DatumWriter<affiliation_updated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<affiliation_updated>
    READER$ = (org.apache.avro.io.DatumReader<affiliation_updated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










