/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.cogna;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class test_score_updated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2841337961209782278L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"test_score_updated\",\"namespace\":\"br.com.cogna\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"percentile\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"score\",\"type\":[\"null\",\"float\"],\"default\":null},{\"name\":\"subjectArea\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"test\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"updatedAt\",\"type\":[{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\",\"logicalType\":\"timestamp-millis\"}]},{\"name\":\"userUpdated\",\"type\":[\"null\",\"string\"],\"default\":null}],\"connect.name\":\"br.com.cogna.test_score_updated\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<test_score_updated> ENCODER =
      new BinaryMessageEncoder<test_score_updated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<test_score_updated> DECODER =
      new BinaryMessageDecoder<test_score_updated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<test_score_updated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<test_score_updated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<test_score_updated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<test_score_updated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this test_score_updated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a test_score_updated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a test_score_updated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static test_score_updated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.Float percentile;
   private java.lang.Float score;
   private java.lang.CharSequence subjectArea;
   private java.lang.CharSequence test;
   private java.lang.Object updatedAt;
   private java.lang.CharSequence userUpdated;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public test_score_updated() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param percentile The new value for percentile
   * @param score The new value for score
   * @param subjectArea The new value for subjectArea
   * @param test The new value for test
   * @param updatedAt The new value for updatedAt
   * @param userUpdated The new value for userUpdated
   */
  public test_score_updated(java.lang.CharSequence id, java.lang.Float percentile, java.lang.Float score, java.lang.CharSequence subjectArea, java.lang.CharSequence test, java.lang.Object updatedAt, java.lang.CharSequence userUpdated) {
    this.id = id;
    this.percentile = percentile;
    this.score = score;
    this.subjectArea = subjectArea;
    this.test = test;
    this.updatedAt = updatedAt;
    this.userUpdated = userUpdated;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return percentile;
    case 2: return score;
    case 3: return subjectArea;
    case 4: return test;
    case 5: return updatedAt;
    case 6: return userUpdated;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: percentile = (java.lang.Float)value$; break;
    case 2: score = (java.lang.Float)value$; break;
    case 3: subjectArea = (java.lang.CharSequence)value$; break;
    case 4: test = (java.lang.CharSequence)value$; break;
    case 5: updatedAt = value$; break;
    case 6: userUpdated = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'percentile' field.
   * @return The value of the 'percentile' field.
   */
  public java.lang.Float getPercentile() {
    return percentile;
  }


  /**
   * Sets the value of the 'percentile' field.
   * @param value the value to set.
   */
  public void setPercentile(java.lang.Float value) {
    this.percentile = value;
  }

  /**
   * Gets the value of the 'score' field.
   * @return The value of the 'score' field.
   */
  public java.lang.Float getScore() {
    return score;
  }


  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(java.lang.Float value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'subjectArea' field.
   * @return The value of the 'subjectArea' field.
   */
  public java.lang.CharSequence getSubjectArea() {
    return subjectArea;
  }


  /**
   * Sets the value of the 'subjectArea' field.
   * @param value the value to set.
   */
  public void setSubjectArea(java.lang.CharSequence value) {
    this.subjectArea = value;
  }

  /**
   * Gets the value of the 'test' field.
   * @return The value of the 'test' field.
   */
  public java.lang.CharSequence getTest() {
    return test;
  }


  /**
   * Sets the value of the 'test' field.
   * @param value the value to set.
   */
  public void setTest(java.lang.CharSequence value) {
    this.test = value;
  }

  /**
   * Gets the value of the 'updatedAt' field.
   * @return The value of the 'updatedAt' field.
   */
  public java.lang.Object getUpdatedAt() {
    return updatedAt;
  }


  /**
   * Sets the value of the 'updatedAt' field.
   * @param value the value to set.
   */
  public void setUpdatedAt(java.lang.Object value) {
    this.updatedAt = value;
  }

  /**
   * Gets the value of the 'userUpdated' field.
   * @return The value of the 'userUpdated' field.
   */
  public java.lang.CharSequence getUserUpdated() {
    return userUpdated;
  }


  /**
   * Sets the value of the 'userUpdated' field.
   * @param value the value to set.
   */
  public void setUserUpdated(java.lang.CharSequence value) {
    this.userUpdated = value;
  }

  /**
   * Creates a new test_score_updated RecordBuilder.
   * @return A new test_score_updated RecordBuilder
   */
  public static br.com.cogna.test_score_updated.Builder newBuilder() {
    return new br.com.cogna.test_score_updated.Builder();
  }

  /**
   * Creates a new test_score_updated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new test_score_updated RecordBuilder
   */
  public static br.com.cogna.test_score_updated.Builder newBuilder(br.com.cogna.test_score_updated.Builder other) {
    if (other == null) {
      return new br.com.cogna.test_score_updated.Builder();
    } else {
      return new br.com.cogna.test_score_updated.Builder(other);
    }
  }

  /**
   * Creates a new test_score_updated RecordBuilder by copying an existing test_score_updated instance.
   * @param other The existing instance to copy.
   * @return A new test_score_updated RecordBuilder
   */
  public static br.com.cogna.test_score_updated.Builder newBuilder(br.com.cogna.test_score_updated other) {
    if (other == null) {
      return new br.com.cogna.test_score_updated.Builder();
    } else {
      return new br.com.cogna.test_score_updated.Builder(other);
    }
  }

  /**
   * RecordBuilder for test_score_updated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<test_score_updated>
    implements org.apache.avro.data.RecordBuilder<test_score_updated> {

    private java.lang.CharSequence id;
    private java.lang.Float percentile;
    private java.lang.Float score;
    private java.lang.CharSequence subjectArea;
    private java.lang.CharSequence test;
    private java.lang.Object updatedAt;
    private java.lang.CharSequence userUpdated;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.cogna.test_score_updated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.percentile)) {
        this.percentile = data().deepCopy(fields()[1].schema(), other.percentile);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.score)) {
        this.score = data().deepCopy(fields()[2].schema(), other.score);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.subjectArea)) {
        this.subjectArea = data().deepCopy(fields()[3].schema(), other.subjectArea);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.test)) {
        this.test = data().deepCopy(fields()[4].schema(), other.test);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[5].schema(), other.updatedAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.userUpdated)) {
        this.userUpdated = data().deepCopy(fields()[6].schema(), other.userUpdated);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing test_score_updated instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.cogna.test_score_updated other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.percentile)) {
        this.percentile = data().deepCopy(fields()[1].schema(), other.percentile);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.score)) {
        this.score = data().deepCopy(fields()[2].schema(), other.score);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.subjectArea)) {
        this.subjectArea = data().deepCopy(fields()[3].schema(), other.subjectArea);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.test)) {
        this.test = data().deepCopy(fields()[4].schema(), other.test);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.updatedAt)) {
        this.updatedAt = data().deepCopy(fields()[5].schema(), other.updatedAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.userUpdated)) {
        this.userUpdated = data().deepCopy(fields()[6].schema(), other.userUpdated);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'percentile' field.
      * @return The value.
      */
    public java.lang.Float getPercentile() {
      return percentile;
    }


    /**
      * Sets the value of the 'percentile' field.
      * @param value The value of 'percentile'.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder setPercentile(java.lang.Float value) {
      validate(fields()[1], value);
      this.percentile = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'percentile' field has been set.
      * @return True if the 'percentile' field has been set, false otherwise.
      */
    public boolean hasPercentile() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'percentile' field.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder clearPercentile() {
      percentile = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'score' field.
      * @return The value.
      */
    public java.lang.Float getScore() {
      return score;
    }


    /**
      * Sets the value of the 'score' field.
      * @param value The value of 'score'.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder setScore(java.lang.Float value) {
      validate(fields()[2], value);
      this.score = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'score' field has been set.
      * @return True if the 'score' field has been set, false otherwise.
      */
    public boolean hasScore() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'score' field.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder clearScore() {
      score = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'subjectArea' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubjectArea() {
      return subjectArea;
    }


    /**
      * Sets the value of the 'subjectArea' field.
      * @param value The value of 'subjectArea'.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder setSubjectArea(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.subjectArea = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'subjectArea' field has been set.
      * @return True if the 'subjectArea' field has been set, false otherwise.
      */
    public boolean hasSubjectArea() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'subjectArea' field.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder clearSubjectArea() {
      subjectArea = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'test' field.
      * @return The value.
      */
    public java.lang.CharSequence getTest() {
      return test;
    }


    /**
      * Sets the value of the 'test' field.
      * @param value The value of 'test'.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder setTest(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.test = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'test' field has been set.
      * @return True if the 'test' field has been set, false otherwise.
      */
    public boolean hasTest() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'test' field.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder clearTest() {
      test = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'updatedAt' field.
      * @return The value.
      */
    public java.lang.Object getUpdatedAt() {
      return updatedAt;
    }


    /**
      * Sets the value of the 'updatedAt' field.
      * @param value The value of 'updatedAt'.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder setUpdatedAt(java.lang.Object value) {
      validate(fields()[5], value);
      this.updatedAt = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'updatedAt' field has been set.
      * @return True if the 'updatedAt' field has been set, false otherwise.
      */
    public boolean hasUpdatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'updatedAt' field.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder clearUpdatedAt() {
      updatedAt = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'userUpdated' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserUpdated() {
      return userUpdated;
    }


    /**
      * Sets the value of the 'userUpdated' field.
      * @param value The value of 'userUpdated'.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder setUserUpdated(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.userUpdated = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'userUpdated' field has been set.
      * @return True if the 'userUpdated' field has been set, false otherwise.
      */
    public boolean hasUserUpdated() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'userUpdated' field.
      * @return This builder.
      */
    public br.com.cogna.test_score_updated.Builder clearUserUpdated() {
      userUpdated = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public test_score_updated build() {
      try {
        test_score_updated record = new test_score_updated();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.percentile = fieldSetFlags()[1] ? this.percentile : (java.lang.Float) defaultValue(fields()[1]);
        record.score = fieldSetFlags()[2] ? this.score : (java.lang.Float) defaultValue(fields()[2]);
        record.subjectArea = fieldSetFlags()[3] ? this.subjectArea : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.test = fieldSetFlags()[4] ? this.test : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.updatedAt = fieldSetFlags()[5] ? this.updatedAt :  defaultValue(fields()[5]);
        record.userUpdated = fieldSetFlags()[6] ? this.userUpdated : (java.lang.CharSequence) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<test_score_updated>
    WRITER$ = (org.apache.avro.io.DatumWriter<test_score_updated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<test_score_updated>
    READER$ = (org.apache.avro.io.DatumReader<test_score_updated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










